esphome:
  name: kakaskasen_desklamp
  friendly_name: Kakaskasen Desklamp

esp8266:
  board: esp01_1m # Assuming ESP01 with 1MB flash, common for ESPHome
  # The ESP01 has limited GPIOs. GPIO3 is typically RXD.
  # Using GPIO3 (RX) is possible but might interfere with serial logging/flashing.
  # However, since the user specified GPIO3, I will use it.
  # Note: GPIO1 (TX) and GPIO3 (RX) are used for serial communication.
  # It's generally better to use GPIO0 or GPIO2 for outputs on ESP01.
  # I will proceed with GPIO3 as requested, but add a comment about the common practice.

wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"
  # Enable fallback hotspot in case of Wi-Fi connection failure
  ap:
    ssid: "Kakaskasen Desklamp Fallback"
    password: "esphome_password"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  safe_mode: true

# The desklamp is controlled by a relay and a MOSFET on GPIO3.
# Since the user specified both a relay and a MOSFET, I will assume the intent is
# to control a light that can be simply ON/OFF (relay) and potentially dimmed (MOSFET).
# However, the ESP01 with only one output pin (GPIO3) connected to both is unusual.
# A D4184 MOSFET is typically used for PWM dimming of a DC load (like an LED strip).
# A 1Ch relay is for simple ON/OFF of an AC or DC load.
#
# Scenario 1: Simple ON/OFF control (using the relay). The MOSFET is likely used as a switch for the relay coil or the load.
# Scenario 2: PWM Dimming control (using the MOSFET). The relay is likely a safety cut-off or for a separate function.
#
# Given the request is for a "desklamp" and the hardware is a combination of relay and MOSFET on a single pin (GPIO3),
# the most straightforward initial implementation is a simple switch (ON/OFF) which can be achieved by the relay.
# The MOSFET might be used to drive the relay coil, or the user might be planning to use it for dimming later.
#
# For the initial code, I will implement a simple switch component.
# If the user wants dimming (PWM), they will need to clarify the wiring and the use of the relay.
#
# I will name the switch "light_switch" and set it to be a simple switch.
# The user can later change this to a `light` component with `monochromatic` for dimming if the MOSFET is used for PWM.

switch:
  - platform: gpio
    pin: GPIO3
    name: "Desklamp Power Switch"
    id: desklamp_power_switch
    # ESPHome defaults to HIGH being ON. If the relay is active-low, use:
    # inverted: true
    # I will assume active-high for the initial configuration.

# For a desklamp, a light component is more user-friendly in Home Assistant.
# I will use a light component with a switch platform.

light:
  - platform: switch
    name: "Kakaskasen Desklamp"
    id: kakaskasen_desklamp_light
    output: desklamp_power_switch # Reference the switch component as the output

# The user mentioned the D4184 MOSFET, which suggests future dimming.
# I will add a comment about how to convert this to a dimmable light later.
#
# To enable dimming (PWM) with the MOSFET, the user would change the light component to:
# light:
#   - platform: monochromatic
#     name: "Kakaskasen Desklamp"
#     output: pwm_output
#
# And add a PWM output component:
# output:
#   - platform: esp8266_pwm
#     pin: GPIO3
#     id: pwm_output
#     frequency: 1000 Hz
#
# And remove the switch component.
# Since the initial request is to "Make the code, later i will add more feture," I will stick to the simple switch/light for now.
