substitutions:
  name: node1-desklamp1
  friendly_name: node1-desklamp1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

logger:
  level: ERROR

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: "139139~~"

captive_portal:

web_server:
  port: 80
  version: 2

time:
  - platform: homeassistant
    id: esptime

status_led:
  pin:
    number: 2
    inverted: False

api:
  encryption:
    key: "Vtm4Px86yE7LgdC7gkrbI5kNTNGDuLM3UZ4mew7bkMo="
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: "2d62244917b52a531f94a3b43259515f"

button:
  - platform: restart
    id: restart_button
    name: 'Restart ${friendly_name}'
    entity_category: "config"

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: wifi_signal
    id: wifi_signal_strength
    update_interval: 60s
    name: WLAN Signal
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

  - platform: template
    name: WLAN Channel
    id: wifi_channel
    lambda: return WiFi.channel();
    update_interval: 60s
    entity_category: "diagnostic"
    accuracy_decimals: 0

  - platform: uptime
    name: Uptime
    id: 'upptime'
    internal: True
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(upptime).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "WLAN IP"
    ssid:
      name: "WLAN SSID"
    bssid:
      name: "WLAN BSSID"
    mac_address:
      name: "WLAN MAC"
    dns_address:
      name: "WLAN DNS"

  - platform: version
    name: ${friendly_name} Version
    hide_timestamp: true
    icon: mdi:new-box
    entity_category: "config"

  - platform: template
    name: ${friendly_name} Uptime
    id: uptime_human
    icon: mdi:clock-start
    entity_category: "diagnostic"
    device_class: ""

# Desklamp Control - Core Functionality
# ESP01+1Ch relay+D4184 Mosfet module conected in GPIO3.
# This is configured as a simple ON/OFF switch using the GPIO pin.

switch:
  - platform: gpio
    pin: GPIO3
    name: "Desklamp Power Switch"
    id: desklamp_power_switch
    # ESPHome defaults to HIGH being ON. If the relay is active-low, use:
    # inverted: true

light:
  - platform: switch
    name: "${friendly_name} Light"
    id: desklamp_light
    output: desklamp_power_switch

# Note on GPIO3: This pin is typically used for serial communication (RX) on the ESP01.
# While it can be used as an output, it might interfere with serial logging or flashing.
#
# Note on MOSFET (D4184): This component suggests future dimming (PWM).
# To enable dimming, you would change the light component to:
# light:
#   - platform: monochromatic
#     name: "${friendly_name} Light"
#     output: pwm_output
#
# And add a PWM output component:
# output:
#   - platform: esp8266_pwm
#     pin: GPIO3
#     id: pwm_output
#     frequency: 1000 Hz
#
# And remove the switch component.
