substitutions:
  name: node1-desklamp1
  friendly_name: node1-desklamp1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

logger:
  level: ERROR

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: "139139~~"

captive_portal:

web_server:
  port: 80
  version: 2

time:
  - platform: homeassistant
    id: esptime

# Status LED moved to GPIO0 to free up GPIO2 for the MOSFET.
# Note: GPIO0 is used for boot mode selection (must be HIGH or floating for normal boot).
# Ensure the status LED circuit does not pull GPIO0 low during boot.
status_led:
  pin:
    number: 0
    inverted: False

api:
  encryption:
    key: "Vtm4Px86yE7LgdC7gkrbI5kNTNGDuLM3UZ4mew7bkMo="
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: "2d62244917b52a531f94a3b43259515f"

button:
  - platform: restart
    id: restart_button
    name: 'Restart ${friendly_name}'
    entity_category: "config"

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  # Touch Switch on GPIO1 (TX)
  - platform: gpio
    pin:
      number: 1
      mode: INPUT_PULLUP # Assuming a common touch switch module that pulls the pin low when touched
      inverted: True # Invert so that a touch (LOW) registers as ON
    name: "Desklamp Touch Switch"
    on_press:
      then:
        - light.toggle: desklamp_light

sensor:
  - platform: wifi_signal
    id: wifi_signal_strength
    update_interval: 60s
    name: WLAN Signal
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

  - platform: template
    name: WLAN Channel
    id: wifi_channel
    lambda: return WiFi.channel();
    update_interval: 60s
    entity_category: "diagnostic"
    accuracy_decimals: 0

  - platform: uptime
    name: Uptime
    id: 'upptime'
    internal: True
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(upptime).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "WLAN IP"
    ssid:
      name: "WLAN SSID"
    bssid:
      name: "WLAN BSSID"
    mac_address:
      name: "WLAN MAC"
    dns_address:
      name: "WLAN DNS"

  - platform: version
    name: ${friendly_name} Version
    hide_timestamp: true
    icon: mdi:new-box
    entity_category: "config"

  - platform: template
    name: ${friendly_name} Uptime
    id: uptime_human
    icon: mdi:clock-start
    entity_category: "diagnostic"
    device_class: ""

# Desklamp Control - Separate Relay and MOSFET Control
#
# GPIO3 (RX) for the 1Ch Relay (Simple ON/OFF)
# GPIO2 for the D4184 MOSFET (PWM Dimming)
#
# NOTE: GPIO3 is used for serial communication (RX). You may need to disconnect the relay
# when flashing new firmware.
# NOTE: GPIO2 must be HIGH during boot. Ensure your MOSFET circuit does not interfere.
# NOTE: GPIO1 is used for serial communication (TX). You may need to disconnect the touch switch
# when flashing new firmware.

# 1. Relay Control (Simple ON/OFF) on GPIO3
switch:
  - platform: gpio
    pin: GPIO3
    name: "Desklamp Relay Switch"
    id: desklamp_relay_switch
    # If your relay is active-low, uncomment the line below:
    # inverted: true

# 2. MOSFET Control (PWM Dimming) on GPIO2
output:
  - platform: esp8266_pwm
    pin: GPIO2
    id: pwm_output
    frequency: 1000 Hz
    inverted: true

# 3. Combined Light Component for Home Assistant
# This creates a single light entity in Home Assistant that has both ON/OFF (via relay)
# and brightness control (via MOSFET).
light:
  - platform: monochromatic
    name: "${friendly_name} Light"
    id: desklamp_light
    output: pwm_output
    max_power: 0.8
    # The relay is wired to the same light circuit as a safety/master switch.
    # We can use a custom template to ensure the relay is always ON when the light is ON,
    # and OFF when the light is OFF.
    # This is a common pattern for combining a relay and a dimmer.
    on_turn_on:
      - switch.turn_on: desklamp_relay_switch
    on_turn_off:
      - switch.turn_off: desklamp_relay_switch
